### ISSUE TITLE
UI improvement: replace scrollbars

### ISSUE THREAD

**Issue by supertorpe** [micrusa/AmazTimer#8]
The scrollbars for setting weight (kg) and age are very unwieldy on the watch screen. It is almost impossible to select specific values since a small displacement of the finger results in a jump of several values.
I suggest replacing them with the "-" and "+" controls that are used to set the work/rest duration.

**Comment by micrusa** [comment]
Changed in https://github.com/micrusa/AmazTimer/commit/c1d9342110f542ca7ec3bbb93c4a60bad04d11ec
Now I'm using a ListPreference instead of a SeekBarPreference, I didn't replace it with + and - controls because I would have to create a new preference and it's easier this way. I will release a new version with this and other changes tomorrow maybe
